#!/bin/bash

BIDS_DIR=$AUTOBIDS_DATA/Ansari/Intergenerational/bids
SUBJ_EXPR=*_{subject}  #search string in patient_name

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/intergen_heuristic.py

#POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T

GLOBUS_BIDS_ENDPOINT=a8155c03-568b-4bef-9eb7-5fd39a39c100
EMAIL_NOTIFICATION=switt4@uwo.ca,lien.peters4@gmail.com
TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.5c`
