#!/bin/bash

BIDS_DIR=$AUTOBIDS_DATA/Bodell/PeerStudy/bids
SUBJ_EXPR=*_{subject}  #search string in patient_name

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/peerstudy_heuristic.py

GLOBUS_BIDS_ENDPOINT=c5e1dabb-2bf0-4511-815b-0b6c7806c60c
EMAIL_NOTIFICATION=switt4@uwo.ca,clowe3@uwo.ca
TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.5c`
