#!/bin/bash

BIDS_DIR=$AUTOBIDS_DATA/Burneo/EpLinkPhase3_Baseline/bids_2022
SUBJ_EXPR=*_[lL][hH][sS]_{subject}  #search string in patient_name

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/cfmm_base_hippdwi_boldrestmovie.py

TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.6a`
#POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/postproc3T.v0.2

GLOBUS_BIDS_ENDPOINT=76e505a8-faba-11e9-9945-0a8c187e8c12
EMAIL_NOTIFICATION=alik@robarts.ca
