#!/bin/bash

BIDS_DIR=$AUTOBIDS_DATA/Burneo/EpLinkPhase3_Baseline/bids
SUBJ_EXPR=*_[lL][hH][sS]_{subject}  #search string in patient_name

HEURISTIC=cfmm_bold_rest.py

TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.5a`
POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/postproc3T.v0.2

GLOBUS_BIDS_ENDPOINT=76e505a8-faba-11e9-9945-0a8c187e8c12
EMAIL_NOTIFICATION=alik@robarts.ca,cmantei@uwo.ca
