#!/bin/bash

BIDS_DIR=$AUTOBIDS_DATA/Butler/Misophonia/bids
SUBJ_EXPR=*_{subject}  #search string in patient_name

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/misophonia_heuristic.py

POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/postproc3T.v0.2

GLOBUS_BIDS_ENDPOINT=34c03a70-dd8e-4a53-8854-52e28d0cc38d
EMAIL_NOTIFICATION=switt4@uwo.ca,kraymon9@uwo.ca,bbutler9@uwo.ca
TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.5c`
