#!/bin/bash

BIDS_DIR=$AUTOBIDS_DATA/Culham/ActiveLearn/bids
SUBJ_EXPR=*_{subject}  #search string in patient_name

HEURISTIC="$AUTOBIDS_STUDY_CFG_DIR/../heuristics/activelearn_heuristic.py -D"

POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/postproc3T.v0.2

GLOBUS_BIDS_ENDPOINT=24afd509-3c69-4436-a837-0c6ef2ca9975
EMAIL_NOTIFICATION=switt4@uwo.ca,cbacher3@uwo.ca
TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.5c`
