#!/bin/bash

BIDS_DIR=$AUTOBIDS_DATA/Culham/Pacman/bids
SUBJ_EXPR=*_{subject}  #search string in patient_name

HEURISTIC="$AUTOBIDS_STUDY_CFG_DIR/../heuristics/pacman_heuristic.py -D -U 300"

#POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/postproc3T.v0.2

GLOBUS_BIDS_ENDPOINT=1eb2651e-7da9-4577-b27a-9cf9a2af71ea
EMAIL_NOTIFICATION=switt4@uwo.ca,edavid46@uwo.ca
TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:uniden3T`
