#!/bin/bash

SUBJ_EXPR=*_{subject}  #search string for patientname

#default: 
#BIDS_DIR=$AUTOBIDS_DATA/{PI}/{PROJECT}/bids


HEURISTIC=cfmm_bold_rest.py

#POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T

GLOBUS_BIDS_ENDPOINT=
EMAIL_NOTIFICATION=alik@robarts.ca

TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.5c`
