#!/bin/bash

#BIDS_DIR=$AUTOBIDS_DATA/Diedrichsen/pilotBSP/bids
BIDS_DIR=$AUTOBIDS_DATA/Diedrichsen/BSP/bids
SUBJ_EXPR=*_{subject}  #search string in patient_name

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/mcc_heuristic.py

TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.5c`
#TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.4`
POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T.v0.3

GLOBUS_BIDS_ENDPOINT=f8b1c6d0-3b88-11e9-a613-0a54e005f950
EMAIL_NOTIFICATION=switt4@uwo.ca,cherna3@uwo.ca