#!/bin/bash

SUBJ_EXPR=*_{subject}  #search string for patientname

BIDS_DIR=$AUTOBIDS_DATA/Diedrichsen/SeqRep4/bids

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/seqrep4_heuristic.py

TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.5c`
POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T.v0.3

#GLOBUS_BIDS_ENDPOINT=f82c4e34-57b2-11e8-9104-0a6d4e044368
EMAIL_NOTIFICATION=switt4@uwo.ca,giacomo.ariani@gmail.com

