#!/bin/bash

#BIDS_DIR=$AUTOBIDS_DATA/Diedrichsen/pilotBSP/bids
BIDS_DIR=$AUTOBIDS_DATA/Diedrichsen/BSP/bids
SUBJ_EXPR=*_{subject}  #search string in patient_name

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/mcc_heuristic.py

TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.5c`
#TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.4`
POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T.v0.3

GLOBUS_BIDS_ENDPOINT=b0e280be-0c67-11ea-8a65-0e35e66293c2
EMAIL_NOTIFICATION=switt4@uwo.ca,cherna3@uwo.ca