#!/bin/bash

BIDS_DIR=$AUTOBIDS_DATA/Diedrichsen/Language-Cerebellum/bids
SUBJ_EXPR=*_[Ss][Uu][Bb]{subject}_{session}  #search string in patient_name

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/language_cerebellum_heuristic.py

TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.5c`
#TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.4`
POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T.v0.3

GLOBUS_BIDS_ENDPOINT=948cbb80-4565-4985-b84f-5ab1bfbb5e8a
EMAIL_NOTIFICATION=switt4@uwo.ca,barafat@uwo.ca
