#!/bin/bash

BIDS_DIR=$AUTOBIDS_DATA/Diedrichsen/LanguageCerebellum/bids
SUBJ_EXPR=*_{subject}_{session}  #search string in patient_name

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/language_cerebellum_heuristic.py

TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.5c`
#TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.4`
POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T.v0.3

GLOBUS_BIDS_ENDPOINT=c1b9d04f-49a5-4801-8e5d-a7d6629045cb
EMAIL_NOTIFICATION=switt4@uwo.ca,barafat@uwo.ca
