#!/bin/bash

SUBJ_EXPR=*_{subject}  #search string for patientname


HEURISTIC=cfmm.py

DCM2BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/heudiconv_bids
PRE_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/tuneup_bids
POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/mriqc

GLOBUS_BIDS_ENDPOINT=9bc03c00-89ae-11e7-a97f-22000a92523b:testglobus

EMAIL_NOTIFICATION=alik@robarts.ca

