#!/bin/bash

BIDS_DIR=$AUTOBIDS_DATA/Goodale/PHC_Context/bids
SUBJ_EXPR=*_{subject}  #search string in patient_name

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/phccontext_heuristic.py

#POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T

GLOBUS_BIDS_ENDPOINT=
EMAIL_NOTIFICATION=switt4@uwo.ca