#!/bin/bash

SUBJ_EXPR=*_{subject}  #search string for patientname

BIDS_DIR=$AUTOBIDS_DATA/private/Goodale/ABBI/bids

HEURISTIC=cfmm_base.py


GLOBUS_BIDS_ENDPOINT=
EMAIL_NOTIFICATION=alik@robarts.ca

TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.3d
