#!/bin/bash

BIDS_DIR=$AUTOBIDS_DATA/Goodale/PHC_Context/bids
SUBJ_EXPR=*_{subject}  #search string in patient_name

#HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/phccontext_heuristic.py
HEURISTIC=cfmm_bold_rest.py

TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.4`

GLOBUS_BIDS_ENDPOINT=4d24ebaf-d8a6-4ce3-ba30-484088b67f42
EMAIL_NOTIFICATION=switt4@uwo.ca,d.proklova@gmail.com
