#!/bin/bash

SUBJ_EXPR=*_{subject}  #search string for patientname

BIDS_DIR=$AUTOBIDS_DATA/private/Goodale/ABBI/bids

HEURISTIC=cfmm_base.py


GLOBUS_BIDS_ENDPOINT=
EMAIL_NOTIFICATION=alik@robarts.ca

