#!/bin/bash

BIDS_DIR=$AUTOBIDS_DATA/Hayden/COVID-FollowUp/bids
SUBJ_EXPR=*_{subject}  #search string in patient_name

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/covid_followup_heuristic.py

TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.5c`
#TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.4`
#POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T.v0.3

GLOBUS_BIDS_ENDPOINT=9d2dfe79-29c9-4bb2-be9b-2ab2067b1e67
EMAIL_NOTIFICATION=switt4@uwo.ca,hgreen22@uwo.ca
