#!/bin/bash

BIDS_DIR=$AUTOBIDS_DATA/Hunter/LLA/bids
SUBJ_EXPR=*_{subject}  #search string in patient_name

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/lla_heuristic.py

POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/postproc3T.v0.2

GLOBUS_BIDS_ENDPOINT=
EMAIL_NOTIFICATION=switt4@uwo.ca,smuir4@uwo.ca
TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.5c`
