#!/bin/bash

BIDS_DIR=$AUTOBIDS_DATA/Johnsrude/Music_Language/bids
SUBJ_EXPR=*_{subject}  #search string in patient_name

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/musiclanguage_heuristic.py

#POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T

GLOBUS_BIDS_ENDPOINT=ba349a69-2f51-435c-8676-9ab14feb4d72
EMAIL_NOTIFICATION=switt4@uwo.ca,cdernede@uwo.ca
TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.3d`
