#!/bin/bash

#BIDS_DIR=$AUTOBIDS_DATA/Johnsrude/SpokenStories/bids
BIDS_DIR=/project/6033493/cfmm-bids/Johnsrude/SpokenStories/bids

CC_STORAGE_ALLOC=rrg-conchlab  #overrides the default rrg-akhanf for group ownership

SUBJ_EXPR=*_{subject}  #search string in patient_name

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/spokenstories_heuristic.py

#POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/postproc3T.v0.1

#GLOBUS_BIDS_ENDPOINT=ec2f3d62-b3b4-11e9-98d4-0a63aa6b37da
GLOBUS_BIDS_ENDPOINT=de624398-ba1f-11e9-9cea-0edb67dd7a14
EMAIL_NOTIFICATION=switt4@uwo.ca,ayshamotala6@gmail.com
TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.3d
