#!/bin/bash

SUBJ_EXPR=*_{subject}  #search string for patientname

#default: 
#BIDS_DIR=$AUTOBIDS_DATA/{PI}/{PROJECT}


HEURISTIC=cfmm_base.py


GLOBUS_BIDS_ENDPOINT=
EMAIL_NOTIFICATION=alik@robarts.ca

