#!/bin/bash

SUBJ_EXPR=*_{subject}_{session}  #search string for patientname
BIDS_DIR=/project/6007967/akhanf/cfmm-bids/data/Kohler/HcECT/bids

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/Kohler_HcECT.py

#DCM2BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/heudiconv_bids
#PRE_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/tuneup_bids
#POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T

GLOBUS_BIDS_ENDPOINT=997fbe1a-465b-11e8-8e6f-0a6d4e044368
EMAIL_NOTIFICATION=alik@robarts.ca,schakr28@uwo.ca,mvarvani@uwo.ca

TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.3d
