#!/bin/bash

SUBJ_EXPR=*_{subject}  #search string for patientname


HEURISTIC=cfmm_bold_rest.py

#DCM2BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/heudiconv_bids
#PRE_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/tuneup_bids
POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T_mriqc

GLOBUS_BIDS_ENDPOINT=997fbe1a-465b-11e8-8e6f-0a6d4e044368
EMAIL_NOTIFICATION=alik@robarts.ca,schakr28@uwo.ca

