#!/bin/bash

BIDS_DIR=$AUTOBIDS_DATA/MacDonald/7T_RS_Movie/bids
SUBJ_EXPR=*_{subject}  #search string in patient_name

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/rsstandards_heuristic.py

TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.5c`
POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T.v0.3

GLOBUS_BIDS_ENDPOINT=fe11c55e-5899-4a5d-a66b-69c9430d9d29
EMAIL_NOTIFICATION=switt4@uwo.ca,kvanhedg@uwo.ca
