#!/bin/bash

BIDS_DIR=$AUTOBIDS_DATA/Menon/MentalChron/
SUBJ_EXPR=*_[sS][uU][bB][jJ]_{subject}  #search string in patient_name

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/mentalchron_heuristic.py

TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.4`
POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T

GLOBUS_BIDS_ENDPOINT=eae0f0b8-2bb5-11e9-9351-0e3d676669f4
EMAIL_NOTIFICATION=switt4@uwo.ca
