#!/bin/bash

BIDS_DIR=$AUTOBIDS_DATA/Menon/MentalChron/
SUBJ_EXPR=*_[subj]_{subject}_{session}  #search string in patient_name

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/mentalchron_heuristic.py

#POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T_mriqc

GLOBUS_BIDS_ENDPOINT=85962388-2af0-11e9-9836-0262a1f2f698
EMAIL_NOTIFICATION=switt4@uwo.ca,z.fazal@donder.ru.nl