#!/bin/bash

SUBJ_EXPR=*[cC_]{subject}[_-]{session}


BIDS_DIR=$AUTOBIDS_DATA/private/Menon/CogMS/bids-temp

#HEURISTIC=Menon_CogMS.py

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/Menon_CogMSv2.py

#POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T
POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T.v0.3
#TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.5c`
#TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.1.3`
TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.6b`

GLOBUS_BIDS_ENDPOINT=5f8c7bf6-5076-11e8-9021-0a6d4e044368
EMAIL_NOTIFICATION=alik@robarts.ca; switt4@uwo.ca

