#!/bin/bash

#BIDS_DIR=$AUTOBIDS_DATA/Mohsenzadeh/Mental_Imagery/bids
BIDS_DIR=/project/6059441/cfmm-bids/Mohsenzadeh/Mental_Imagery/bids
SUBJ_EXPR=*_{subject}_{session}  #search string in patient_name

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/mentalimagery_heuristic.py

TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.5c`
#POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T.v0.3

GLOBUS_BIDS_ENDPOINT=1e9f6b69-1c15-4a37-8721-d6f6c48ead66
EMAIL_NOTIFICATION=switt4@uwo.ca,yhu584@uwo.ca
