#!/bin/bash

BIDS_DIR=$AUTOBIDS_DATA/Morton/BSF/bids
SUBJ_EXPR=*_{subject}_{session}  #search string in patient_name

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/bsf_heuristic.py

TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.5c`
POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/postproc3T.v0.1

GLOBUS_BIDS_ENDPOINT=e9e1b9f1-98e5-4b01-981c-bdcf295e9e62
EMAIL_NOTIFICATION=switt4@uwo.ca,clowe3@uwo.ca
