#!/bin/bash

BIDS_DIR=$AUTOBIDS_DATA/Palaniyappan/TOPSYII/bids
SUBJ_EXPR=*[tT][oO][pP][sS][yY]_{subject}_{session}  #search string for patientname

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/topsy2_heuristic.py

POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T.v0.3

EMAIL_NOTIFICATION=switt4@uwo.ca,rlimongi@uwo.ca
GLOBUS_BIDS_ENDPOINT=9c77051c-0d62-11eb-81ae-0e2f230cc907
TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.5c`