#!/bin/bash

BIDS_DIR=/project/6033503/cfmm-bids/Palaniyappan/TOPSY2/bids

#options for renaming the tar file (parses patientname and renames, using default session if none provided)
RENAMER_PARSE_PATIENTNAME='(?:[\w]*)(?<=[Tt][Oo][Pp][Ss][Yy][2]_)(?P<subject>[A-Za-z0-9]+)_*(?P<session>[A-Za-z0-9]+)*)'
RENAMER_FORMAT_STRING='{pi}_{project}_{yyyymmdd}_{subject}_{session}_{instance}.{hash}.{extension}'
RENAMER_DEFAULT_SESSION='01'

#subject expression to use after renaming
SUBJ_EXPR='{subject}_{session}'  #search string for patientname


#HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/topsy2_heuristic.py
HEURISTIC=cfmm_bold_rest.py

POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T.v0.3

EMAIL_NOTIFICATION=switt4@uwo.ca,rlimongi@uwo.ca
GLOBUS_BIDS_ENDPOINT=bd3a84df-4f5d-4161-954c-0979c0c62e20
TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.5c`
