#!/bin/bash

BIDS_DIR=$AUTOBIDS_DATA/Palaniyappan/rTMS/bids
SUBJ_EXPR=*_{subject}  #search string in patient_name

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/rTMS_heuristic.py

POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/postproc3T.v0.2

GLOBUS_BIDS_ENDPOINT=f90a3195-88a9-4730-be43-ae3a57acfaa3
EMAIL_NOTIFICATION=switt4@uwo.ca,jpenner7@uwo.ca
TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.5c`
