#!/bin/bash


SUBJ_EXPR=*[tT][oO][pP][sS][yY]_{subject}  #search string for patientname
#SUBJ_EXPR=*.TOPSY.{subject}.*.*  #search string inside tar (from student HD)


HEURISTIC=cfmm_bold_rest.py

DCM2BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/heudiconv_bids
PRE_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/tuneup_bids
#POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/mriqc

EMAIL_NOTIFICATION=alik@robarts.ca


TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.3d
