#!/bin/bash

#9.4T ex-vivo specimens

SUBJ_EXPR=*_{subject}_{session}  #search string for patientname

BIDS_DIR=$AUTOBIDS_DATA/Peters/tle9.4T_phase2/bids

HEURISTIC=cfmm_bruker.py


GLOBUS_BIDS_ENDPOINT=
EMAIL_NOTIFICATION=alik@robarts.ca

TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.3d
