#!/bin/bash

#9.4T ex-vivo specimens

SUBJ_EXPR=*_{subject}_{session}  #search string for patientname

BIDS_DIR=$AUTOBIDS_DATA/Peters/tle9.4T_phase2

HEURISTIC=cfmm_bruker.py

#POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T_mriqc

GLOBUS_BIDS_ENDPOINT=
EMAIL_NOTIFICATION=alik@robarts.ca

