#!/bin/bash

SUBJ_EXPR=*_{subject}  #search string for patientname


HEURISTIC=cfmm_base.py

#POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/mriqc
POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T

EMAIL_NOTIFICATION=alik@robarts.ca

TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.3d
