#!/bin/bash

BIDS_DIR=$AUTOBIDS_DATA/Pruszynski/NHP_Anaesthesia/bids
SUBJ_EXPR=*_[nN][hH][pP]_{subject} #search string in patient_name

HEURISTIC=$AUTOBIDS_STUDY_CFG_DIR/../heuristics/nhpanaesthesia_heuristic.py

TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.4`
POST_BIDS_PIPELINE=$AUTOBIDS_DIR/pipelines/correct7T.v0.3

GLOBUS_BIDS_ENDPOINT=12ac3b00-3f54-11e9-a618-0a54e005f950
EMAIL_NOTIFICATION=switt4@uwo.ca
#EMAIL_NOTIFICATION=switt4@uwo.ca,mverma8@uwo.ca