#!/bin/bash

SUBJ_EXPR=*_MRI{subject}  #search string for patientname

#default: 
BIDS_DIR=/project/6050199/akhanf/cfmm-bids/data/Teeter/Mom_MoP/bids


HEURISTIC=cfmm_base.py

POST_BIDS_PIPELINE=/project/6050199/akhanf/cfmm-bids/data/Teeter/Mom_MoP/etc/postproc3T


GLOBUS_BIDS_ENDPOINT=250b70c0-0f0c-11eb-893c-0a5521ff3f4b
EMAIL_NOTIFICATION=alik@robarts.ca

TAR2BIDS_IMG=`shub-cache docker://khanlab/tar2bids:v0.0.5g`

